### PR TITLE
??!?!

### PR DESCRIPTION
**Pull request by cire3wastaken**
Add:
Modular System for message/packet processing
Refactor
PacketManager
and more

### CODE REVIEW

**Comment by ProdPreva1l** [comment]
ill need to get a better look at the code, but seems alright

**Comment by cire3wastaken** [comment]
Alright, contact me if you have any questions

**Comment by cire3wastaken** [comment]
shoot

**Comment by cire3wastaken** [comment]
Don't merge, let me finish the refactor to the new system first.

**Pull request merged**
